# Config file for Beaconz
world:
  # Beaconz world
  name: beaconz   
  
  # Distribution of beacons the large the number, the more beacons are made
  distribution: 0.03
  
  # Size of the world - a barrier will be created using worldborder if size > 0
  size: 2000
  
  # Distance between new game regions. Must be at least size of the barrier
  # This is the default size for the sides of each new (square) game region
  distance: 2000
  
  # 
  # Coordinates for the lobby area
  # These coordinates must be divisible by 16, otherwise they will be adjusted
  lobbyx: 0
  lobbyz: 0
  lobbyradius: 16 
  
  # Starting center point
  xcenter: 1000
  zcenter: 1000
  
  # Team chat
  # If true, players can only converse with same team players in the beaconz world
  teamchat: false
  
  # Random spawn - if true, players will spawn randomly (within the world border if set)
  randomspawn: false
  
  # Seed adjustment
  seedadjustment: 0
  
  # The base distance in blocks that players can link beacons without experience points
  # If set to -1, beacons can be any distance apart
  linkdistance: 0
  
  # The distance that each exp point will go when linking a beacon
  # If zero, there is no exp cost to link beacons
  expdistance: 5
  
  # Defense height - max height of blocks that can be placed around a beacon
  defenseheight: 8
  
  # Defense levels
  # Defines what levels are required to place a block at the height around the beacon
  # The numbers listed should correspond to their defenseheight. If a number is missing
  # the previous level will be used. A level of 0 means any level can place.
  defenselevel:
     1: 0
     2: 2
     3: 5
     4: 10
     5: 15
     6: 20
     7: 25
     8: 30
     
  # Attack levels
  # Defines what level an attack must be to be able to mine the block at that level
  # above the beacon. 
  # The numbers listed should correspond to their defenseheight. If a number is missing
  # the previous level will be used. A level of 0 means any level can place.
  attacklevel:
     1: 0
     2: 2
     3: 5
     4: 10
     5: 15
     6: 20
     7: 25
     8: 30  
  
  # Starter inventory
  # Format Material:Qty or Material:Data:Qty
  newbiekit:
  - "DIAMOND_PICKAXE:1"
  #- "SUGAR_CANE:1"
  
  # Beacon mine settings
  # Chance that mining a beacon will result in it becoming exhausted and enter
  # a cool down period
  beaconmineexhaustchance: 10
  
  # Mine cool down - how long a player has to wait until they can try to mine a beacon
  # in minutes
  minecooldown: 1
  
  # Effect if you mine a beacon during the cooldown period. Format is Effect:Amplifier
  # Options are: Blindness, Confusion, Harm, Hunger, Slow, Slow_digging, Weakness, Wither
  # Amplifier is a number, .e.g, 0, 1
  minepenalty:
  - "SLOW_DIGGING:1"

  # Rewards from mining beaconz
  # Format is "Id#/Material:[Durability/Qty]:Qty=%Chance"
  # Reward from mining an enemy beacon. Generally the idea is to give players an
  # incentive to find enemy beaconz and even if they cannot attack them, to mine them
  # Goodies are items not normally available because they are from the nether or end or rare.
  enemygoodies:
  - "EMERALD_BLOCK:1=5"
  - "OBSIDIAN:1=5"
  - "NETHER_STALK:1=5"
  - "SOUL_SAND:1=5"
  - "GHAST_TEAR:1=5"
  - "BLAZE_ROD:1=5"
  - "GLOWSTONE:1=5"
  - "NETHERRACK:4=5"
  - "SPECTRAL_ARROW:1=5"
  - "ENDER_STONE:1=5"
  - "CHORUS_FLOWER:1=5"
  # Mining your own beacon should give you the chance of obtaining a map
  teamgoodies:
  # The map is a beacon map
  - "MAP:1=100"

  # Effects from going into enemy triangle fields
  # Effects are cumulative
  enemyfieldeffects:
    # When in 1 field
    1:
    # Format is "Effect:Amplifier"
    - "HUNGER:1"
    # When in 2 fields
    2:
    - "SLOW_DIGGING:1"
    3:
    - "WEAKNESS:1"
    4:
    - "SLOW:1"
    5:
    - "CONFUSION:1"
    6:
    - "POISON:1"
    7:
    - "BLINDNESS:1"
    8:
    - "WITHER:1"
  friendlyfieldeffects:
    1:
    - "SPEED:1"
    2:
    - "DAMAGE_RESISTANCE:1"
    3:
    - "FAST_DIGGING:1"
    4:
    - "JUMP:1"
    5:
    - "REGENERATION:1"
    6:
    - "HEALTH_BOOST:1"
    7:
    - "NIGHT_VISION:1"
    8:
    - "INVISIBILITY:1"

# Team configuration
default_teams: 2
# Teams have glass colors that can be picked from these. They must be different.
# 0: White Stained Glass
# 1: Orange Stained Glass
# 2: Magenta Stained Glass
# 3: Light Blue Stained Glass
# 4: Yellow Stained Glass
# 5: Lime Stained Glass
# 6: Pink Stained Glass
# 7: Gray Stained Glass
# 8: Light Gray Stained Glass
# 9: Cyan Stained Glass
# 10: Purple Stained Glass
# 11: Blue Stained Glass
# 12: Brown Stained Glass
# 13: Green Stained Glass
# 14: Red Stained Glass
# 15: Black Stained Glass
teams:
  red:
    displayname: "Red"
    glasscolor: 14
  blue:
    displayname: "Blue"
    glasscolor: 11
  white:
    displayname: "White"
    glasscolor: 0
  lightblue:
    displayname: "Lightblue"
    glasscolor: 3
  yellow:
    displayname: "Yellow"
    glasscolor: 4
  lime:
    displayname: "Lime"
    glasscolor: 5
  gray:
    displayname: "Gray"
    glasscolor: 7
  lightgray:
    displayname: "Lightgray"
    glasscolor: 8
  cyan:
    displayname: "Cyan"
    glasscolor: 9       
  purple:
    displayname: "Purple"
    glasscolor: 10
  brown:
    displayname: "Brown"
    glasscolor: 12
  green:
    displayname: "Green"
    glasscolor: 13
  black:
    displayname: "Black"
    glasscolor: 15
  orange:
    displayname: "Orange"
    glasscolor: 1
  magenta:
    displayname: "Magenta"
    glasscolor: 2
  pink:
    displayname: "Pink"
    glasscolor: 6           
# gamemode is strategy or minigame
gamemode: strategy
# possible scores to display on sidebar, for either game mode, are area, beacons, links, triangles
# remember that the sidebar only has 15 lines, if there are many teams there may not be enough room to display all scores
sidebar:
  minigame: area:beacons:links:triangles
  strategy: area:beacons:links:triangles
# the goal must be one of the scores displayed on the sidebar
# a goal value > 0 means the game ends when a team reaches that score; the timer is open-ended and counts up
# a goal value = 0 means the timer counts down and when it reaches 0 the team with the greatest score for that goal wins   
goals:
  minigame: links:0
  strategy: area:100000
# timer in seconds, for when the goal value is greater than zero 
timer:
  minigame: 600
  strategy: 0 
# Number of seconds a player must be stationary before they will be teleported
teleportdelay: 5 