name: Beaconz
main: com.wasteofplastic.beaconz.Beaconz
version: ${version}
description: Capture the beacons game
author: tastybento
load: startup
loadbefore: [Multiverse-Core]
commands:
    beaconz:
        description: Main player command
        aliases: [beacons]
        usage:  |
             /beaconz help
    badmin:
        description: Beaconz admin command
        usage:  |
             /badmin help
permissions:
  beaconz.map.unclaimed:
    description: Can see all unclaimed beacons on a map
    default: op
