# Config file for Beaconz
world:
  # Beaconz world
  name: beaconz
  # Distribution of beacons the large the number, the more beacons are made
  distribution: 0.01
  # Size of the world - a barrier will be created using worldborder if size > 0
  size: 0
  # Center
  xCenter: 0
  zCenter: 0
  # Random spawn - if true, players will spawn randomly (within the world border if set)
  randomspawn: false
  # Seed adjustment
  seedadjustment: 0  
  # Hack cool down - how long a player has to wait until they can try to hack a beacon
  # in minutes
  hackcooldown: 1
  # Rewards from hacking
  # Format is "Id#/Material:[Durability/Qty]:Qty:%Chance"
  enemygoodies:
  - "DIAMOND:1:10"
  - "MOB_SPAWNER:1:2"
  - "GOLD_INGOT:1:15"
  - "DIAMOND_SWORD:1:5"
  - "DISPENSER:1:20"
  - "REDSTONE_BLOCK:1:10"
  teamgoodies:
  - "DIAMOND:1:1"
  - "OBSIDIAN:1:5"
  - "STONE:1:30"
  - "IRON_INGOT:1:5"  
  
