# Config file for Beaconz
world:
  # Beaconz world
  name: beaconz
  # Distribution of beacons the large the number, the more beacons are made
  distribution: 0.08
  # Size of the world - a barrier will be created using worldborder if size > 0
  size: 300
  # Center
  xcenter: 1000
  zcenter: 1000
  # Random spawn - if true, players will spawn randomly (within the world border if set)
  randomspawn: false
  # Seed adjustment
  seedadjustment: 0  
  # Hack cool down - how long a player has to wait until they can try to hack a beacon
  # in minutes
  hackcooldown: 1
  # Effect if you hack during the cooldown period. Format is Effect:Amplifier
  # Options are: Blindness, Confusion, Harm, Hunger, Slow, Slow_digging, Weakness, Wither
  # Amplifier is a number, .e.g, 0, 1
  overhackeffects:
  - "SLOW_DIGGING:1"
  # Rewards from hacking
  # Format is "Id#/Material:[Durability/Qty]:Qty:%Chance"
  enemygoodies:
  - "DIAMOND:1:10"
  - "MOB_SPAWNER:1:2"
  - "GOLD_INGOT:1:15"
  - "DIAMOND_SWORD:1:5"
  - "DISPENSER:1:20"
  - "REDSTONE_BLOCK:1:10"
  teamgoodies:
  - "DIAMOND:1:5"
  - "OBSIDIAN:1:5"
  - "STONE:1:30"
  - "IRON_INGOT:1:5"  
  
